server:
  port: 80
  servlet:
    context-path: /hama/

spring:
  resources:
    static-locations:
      - classpath:static/,file:static/
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3306/hama?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations:
    - classpath:mybatis/mapper/*.xml

app:
  config:
    padPort: 10002
    devPort: 10003